print('*' * 35)
print('Soma de 2 Valores')
print('*' * 35)
n1 = int(input('Favor informe 1ª valor: '))
n2 = int(input('Favor informe 2ª valor: '))
total = n1 + n2
print("*--------------------------------*")
# print('A soma entre',n1, ' e ',n2 , 'do numero digitado foi ', (n1+n2) )
print('A soma entre {} e {} vale {}'.format(n1, n2, total))
print("*--------------------------------*")
