aluno = input('Digite o nome do aluno: ')
nt1 = float(input('Digite primeira nota: '))
nt2 = float(input('Digite segunda nota: '))
m = ((nt1 + nt2) / 2)
print('O {} obteve a média de {}'.format(aluno, m))
